from elasticsearch import Elasticsearch
import json

# Setup Elasticsearch
# This shows how to set it up for a cloud hosted version

# # Password for the 'elastic' user generated by Elasticsearch
# ELASTIC_PASSWORD = "..."
#
# # Found in the 'Manage Deployment' page
# CLOUD_ID = "..."
#
# # Create the client instance
# db = Elasticsearch(cloud_id=CLOUD_ID, basic_auth=("elastic", ELASTIC_PASSWORD))

with open("../config.json") as config_file:
    config = json.load(config_file)

CLOUD_ID = config["lee_cloud"]["Cloud_id"]
API_KEY = config["lee_cloud"]["API_KEY"]

db = Elasticsearch(
    cloud_id=CLOUD_ID,
    api_key=API_KEY
)

customers = [
    {"firstname": "Jennifer", "lastname": "Walters"},
    {"firstname": "Monica", "lastname": "Rambeau"},
    {"firstname": "Carol", "lastname": "Danvers"},
    {"firstname": "Wanda", "lastname": "Maximoff"},
    {"firstname": "Jennifer", "lastname": "Takeda"},
]
for i, customer in enumerate(customers):
    db.create(index="customers", document=customer, id=i)
